name: Android CI

on:
  push:
    branches: ["**"]
  pull_request:
    branches: [ "**" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      working-directory: ./ # Cambia esto si gradlew está en otra ubicación

    - name: Build with Gradle
      run: ./gradlew build
      working-directory: ./ # Cambia esto si es necesario

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v4

    - name: set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      working-directory: ./ # Cambia esto si es necesario

    - name: Run unit tests with Gradle
      run: ./gradlew test
      working-directory: ./ # Cambia esto si es necesario

    - name: Unit Test
      run: ./gradlew testDebugUnitTest
      working-directory: ./ # Cambia esto si es necesario

    - name: Android Test Report
      uses: asadmansr/android-test-report-action@v1.2.0
      if: ${{ always() }} # Para que siempre se ejecute
